### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by paolobros** [fcojgodoy/wp-comment-policy-checkbox#12]
Hi, 
Wordpress does not activate the plugin and generates a "fatal error" message
Parse error: syntax error, unexpected '[' in /web/htdocs/sitename/home/wp-content/plugins/wp-comment-policy-checkbox/admin/wp-comment-policy-checkbox-admin.php on line 99 
Help

**Comment by fcojgodoy** [comment]
Hi,
I think you are using an old PHP version, prior to 5.4 (minimal require for the plugin). I recommend updating PHP, especially for reasons of security and performance.
If this is not the reason, tell me.

**Comment by paolobros** [comment]
Yes. 5.4. Thank you!
