### ISSUE TITLE
Multilingual site

### ISSUE THREAD

**Issue by DoritSauer** [fcojgodoy/wp-comment-policy-checkbox#17]
Hi Francisco,

The translation of the "Accept the privacy policy" sentence works. However, I would need to be able to link to the privacy policy corresponding to the visitor's language. As well, the additional legal text just shows in the language in which I introduce it in Settings/Discussion and I do not find where to translate into the different languages.

**Comment by fcojgodoy** [comment]
This plugin is not multilingual. For now. This Github repo will be removed soon. I open [this issue on GitLab](https://gitlab.com/fcojgodoy/wp-comment-policy-checkbox/issues/19)
